G_COUNTER = 'gcounter'
PN_COUNTER = 'pncounter'
G_SET = 'gset'
TWO_P_SET = '2pset'
LWW_E_SET = 'lwweset'
OR_SET = 'orset'
LWW_REGISTER = 'lwwregister'
MV_REGISTER = 'mvregister'
NULL_TYPE = 'nullltype'
DATA_TYPES = 'datatypes'
DUMMY_KEY = 'dummykey'
CLIENTS = 'clients'

