status_codes = {
    'success': {'message': 'success', 'code': 0},
    'failure': {'message': 'failure', 'code': 1},
    'existing_key': {'message': 'failure', 'code': 2,
                     'description': 'An existing element with the same key found'},
    'data_type_mismatch': {'message': 'failure', 'code': 2,
                           'description': 'the key corresponds to another data type'},
    'missing_key_or_state': {'message': 'failure', 'code': 3,
                             'description': 'Key of counter was missing'},
    'key_not_found': {'message': 'failure', 'code': 4,
                      'description': 'Key/State of counter not found in key/value store'},
    'client_id_not_found': {'message': 'failure', 'code': 5,
                            'description': 'Client ID not found'},
    'existing_client_id': {'message': 'failure', 'code': 6,
                           'description': 'An existing client with same client id was found'},
    'data_type_mismatch': {'message': 'failure', 'code': 7,
                           'description': 'Key/Data Type mismatch'},
    'client_id_not_in_crdt': {'message': 'failure', 'code': 8,
                             'description': 'Client has not been added to CRDT instance'},
    'value_not_found': {'message': 'failure', 'code': 9,
                        'description': 'Value is missing'},
    'timestamp_not_valid': {'message': 'failure', 'code': 10,
                        'description': 'Timestamp value is not valid'},
}
